Hospital Management System/Hospital/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('', include('api.urls'))
]

Hospital Management System/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('getData/', views.getData)
]

Hospital Management System/app/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime, time

def current_date():
    return datetime.now().date()

department_choice=(
        ('cardiology','cardiology'),
        ('dermatology','dermatology'),('pediatrics','pediatrics'),
        ('neurology','neurology'),('gastroenterology','gastroenterology'),
        ('eye-centre','eye-centre'),('ear-nose-throat','ear-nose-throat'),
        ('urology','urology'),('oncology','oncology')
    )

class UserWithUserType(models.Model):
    role_choice=(
        ('patient','patient'),
        ('doctor','doctor')
    )
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    username = models.CharField(max_length=10)
    password = models.CharField(max_length=20)
    email = models.CharField(max_length=30)
    specialist_in = models.CharField(max_length=50,null=True,blank=True,choices=department_choice)
    medical_history = models.TextField(null=True,blank=True)
    gender = models.CharField(max_length=10)
    age = models.CharField(max_length=3,null=True,blank=True)
    address = models.CharField(max_length=50,null=True,blank=True)
    date_of_birth = models.DateField(max_length=100,null=True,blank=True)
    phone_number = models.CharField(max_length=10, blank=True, unique=True,null=True)
    role= models.CharField(max_length=50,choices=role_choice,null=True)

    def __str__(self):
        return self.username

class Appointment(models.Model):
    department = models.CharField(max_length=50, choices=department_choice)
    doctor = models.ForeignKey(UserWithUserType, on_delete=models.CASCADE, limit_choices_to={'role': 'doctor'},default=1, related_name='doctor_appointments')
    appointment_date = models.DateField(default=current_date)
    time_slot = models.CharField(max_length=10,blank=False, null=False)
    patient = models.ForeignKey(UserWithUserType, on_delete=models.CASCADE, limit_choices_to={'role': 'patient'}, related_name='patient_appointment',default=2)
    waitlisted = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.department} - {self.appointment_date} {self.time_slot} Patient: {self.patient.first_name} {self.patient.last_name}"
        
class Feedback(models.Model):
    doctor = models.ForeignKey(UserWithUserType, on_delete=models.CASCADE, limit_choices_to={'role': 'doctor'},related_name='doctor_feedback')
    patient = models.ForeignKey(UserWithUserType, on_delete=models.CASCADE, limit_choices_to={'role': 'patient'}, related_name='patient_feedback')
    rating = models.IntegerField(blank=True, null=True)
    comment = models.TextField(null=True, blank=True)
    response = models.TextField(blank=True, null=True)
    timestamp = models.DateTimeField(auto_now_add=True)

Hospital Management System/templates/appointment_success.html
{% extends 'base.html' %}

{% block content %}
  <h2>Appointment Booked Successfully!</h2>
  <p>Thank you for booking your appointment.</p>
  
{% endblock %}

Hospital Management System/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <title>Text-Editor/IDE Charts</title>
  </head>
  <body>
   {%block scripts%}
   {%endblock scripts%}

   {%block content%}   
   {%endblock content%}   

  </body>
</html>

Hospital Management System/templates/departments.html
{% extends 'nav_bar.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    
</head>
{% block content %}
<body class="departments">
    <h1>Departments</h1>
    <img  src="{% static 'images/departments.jpg' %}">
</body>
{% endblock %}
</html>

Hospital Management System/templates/doc_nav_bar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Navigation Bar</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
    <div class="topnav2">
        <h3>hello, {{request.user}}</h3>
        <!-- <a class="active" href="../doctor_home_page">Home</a> -->
        <a class="active" href="{% url 'logout' %}">Logout</a>
        <a href="{% url 'doctor_feedback' %}">Feedbacks</a>
        <a href="{% url 'doctor_patients' %}">My Patients</a>
        <!-- <a href="../doc_appointments">My Appointments</a> -->
        <a href="{% url 'doctor_profile' %}">My Profile</a>
        <a href="{% url 'doctor_home' %}">Home</a>
    </div>
</body>
{% block content %}
{% endblock %}
</html>

Hospital Management System/templates/edit_appointment.html
{% extends 'patient_nav_bar.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
{% block content %}
<body>
  <div class="editAppointment">
  <h2>Edit Appointment</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Update Appointment</button>
</form>
</div>
</body>
{% endblock %}
</html>

Hospital Management System/templates/edit_doctor_profile.html
{% extends 'doc_nav_bar.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
{% block content %}
<body>
  <div class="editDoctorProfile">
  <h2>Edit Doctor Profile</h2>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="role" value="{{ role }}">
        <div class="container register-form">
          <div class="form">
            <div class="note">
            </div>
    
            <div class="form-content">
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="id_first_name">First Name</label>
                    <p>{{ form.first_name }}</p>
                  </div>
                  <div class="form-group">
                    <label for="id_username">Username</label>
                    <p>{{ form.username }}</p>
                  </div>
                  <div class="form-group">
                    <label for="id_email">Email</label>
                    <p>{{ form.email }}</p>
                  </div>
                  <div class="form-group">
                    <label for="id_phone_number">Phone Number</label>
                    <p>{{ form.phone_number }}</p>
                  </div>
                  <div class="form-group">
                    <label for="id_specialist_in">Specialist In</label>
                    <p>{{ form.specialist_in }}</p>
                  </div>
                  <div class="form-group">
                    <label for="id_role">Role</label>
                    <p>{{ form.role }}</p>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="id_last_name">Last Name</label>
                    <p>{{ form.last_name }}</p>
                  </div>
                  <div class="form-group">
                    <label for="id_password">Password</label>
                    <p>{{ form.password }}</p>
                  </div>
                  <div class="form-group">
                    <label for="id_date_of_birth">Date of birth</label>
                    <p>{{ form.date_of_birth }}</p>
                  </div>
                  <div class="form-group">
                    <label for="id_gender">Gender</label>
                    <p>{{ form.gender }}</p>
                  </div>
                  <div class="form-group">
                    <label for="id_address">Address</label>
                    <p>{{ form.address }}</p>
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <button type="submit">Save Changes</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
      </form>
</div>
</body>
{% endblock %}
</html>

Hospital Management System/templates/login.html
{% extends 'nav_bar.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
{% block content %}
<body>
<br/><br/>
<form action="" method="POST">
  {% csrf_token %}
  <div class="loginbox">
    <h1> Login</h1>

    <label>Username</label>
    <input type="text" name="username">

    <label>Password</label>
    <input type="password" name="password">
    
 
    <a href="{% url 'login' %}"><input type="submit" value="Login"></a>
  

    <p>Do not have an account?</p>
    <a href="../signup/doctor">Signup as Doctor</a><br>
    <a href="../signup/patient"> Signup as Patient</a>
  </div>
</form>
</body>
{% endblock %}
</html>

<!--  {% for field in form %}
          {{field.label}}
          {{field}}
      {% endfor %}

      {% for message in messages %}
          <p>{{message}}</p>
      {% endfor %} -->

Hospital Management System/templates/nav_bar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Navigation Bar</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>

  <body>
    <div class="topnav">
        
        <a href="../contact">Contact</a>
        <a href="../about">About</a>
        <a href="../departments">Departments</a>
        <a href="../doctor_list">Doctors</a>
        <a class="active" href="{% url 'index' %}">Home</a>
    </div>
  </body>
{% block content %}
{% endblock %}
</html>

Hospital Management System/templates/patient_nav_bar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
<body>
    <div class="topnav2">
        <h3>hello, {{request.user}}</h3>
        <a class="active" href="{% url 'logout' %}">Logout</a>
        <a href="{% url 'patient_home' %}">Home</a>
    </div>
</body>
{% block content %}
{% endblock %}
</html>

Hospital Management System/templates/patient_view_feedback.html
{% extends 'patient_nav_bar.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Doctor Page</title>
  <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
{% block content %}
<body>
  <div class="doctorFeedback">
  <h3>Your Feedbacks:</h3>
  <ul>
    {% for feedback in feedbacks %}
      <li>
        <strong>Doctor: </strong> {{ feedback.doctor.first_name }} {{ feedback.patient.last_name }}<br>
        <strong>Rating: </strong> {{ feedback.rating }}<br>
        <strong>Comments: </strong> {{ feedback.comment }}<br>
        <strong>Timestamp: </strong>{{ feedback.timestamp }}<br>
        <strong>Response: </strong>{{ feedback.response }}<br>
      </li>
    {% empty %}
      <li>No feedbacks available.</li>
    {% endfor %}
  </ul>
  <button><a href="{% url 'patient_feedback' %}">Give Feedback</a></button>
</div>
</body>
{% endblock %}
</html>

Hospital Management System/templates/select_department.html
{% extends 'patient_nav_bar.html' %}

{% block content %}
  <h2>Select Department</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Next</button>
  </form>
{% endblock %}

Hospital Management System/templates/select_doctor.html
{% extends 'patient_nav_bar.html' %}

{% block content %}
  <h2>Select Doctor</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Next</button>
  </form>
{% endblock %}

Hospital Management System/templates/user_signup.html
{% extends 'nav_bar.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SignUp page</title>
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
</head>
{% block content %}
<body class="register">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="role" value="{{ role }}">
        <div class="container register-form">
          <div class="form">
            <div class="note">
              <h2>Register</h2>
            </div>
    
            <div class="form-content">
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="id_first_name">First Name</label>
                    <p><input type="text" class="form-control" id="id_first_name" name="first_name"></p>
                  </div>
                  <div class="form-group">
                    <label for="id_username">Username</label>
                    <p><input type="text" class="form-control" id="id_username" name="username"></p>
                  </div>
                  <div class="form-group">
                    <label for="id_email">Email</label>
                    <p><input type="email" class="form-control" id="id_email" name="email"></p>
                  </div>
                  <div class="form-group">
                    <label for="id_phone_number">Phone Number</label>
                    <p><input type="tel" class="form-control" id="id_phone_number" name="phone_number"></p>
                  </div>
                  {% if role == 'doctor' %}
                  <div class="form-group">
                    <label for="id_specialist_in">Specialist In</label>
                    <p><input type="text" class="form-control" id="id_specialist_in" name="specialist_in"></p>
                  </div>
                  {% endif %}
                  {% if role == 'patient' %}
                  <div class="form-group">
                    <label for="id_medical_history">Medical History</label>
                    <p><input type="text" class="form-control" id="id_medical_history" name="medical_history"></p>
                  </div>
                  <div class="form-group">
                    <label for="id_age">Age</label>
                    <p><input type="text" class="form-control" id="id_age" name="age"></p>
                  </div>
                  {% endif %}
                  
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <label for="id_last_name">Last Name</label>
                    <input type="text" class="form-control" id="id_last_name" name="last_name">
                  </div>
                  <div class="form-group">
                    <label for="id_password">Password</label>
                    <input type="password" class="form-control" id="id_password" name="password">
                  </div>
                  <div class="form-group">
                    <label for="id_date_of_birth">Date of birth</label>
                    <input type="date" class="form-control" id="id_date_of_birth" name="date_of_birth">
                  </div>
                  <div class="form-group">
                    <label for="id_gender">Gender</label>
                    <input type="text" class="form-control" id="id_gender" name="gender">
                  </div>
                  <div class="form-group">
                    <label for="id_address">Address</label>
                    <input type="text" class="form-control" id="id_address" name="address">
                  </div>
                  <div class="col-md-6">
                    <div class="form-group">
                      <button type="submit" class="btn-primary">Register</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
      </form>
</body>
{% endblock %}
</html>

Hospital Management System/templates/waitlist.html
<div class="time-slots">
    {% for time_slot in booked_time_slots %}
    <button name="time_slot" value="{{ time_slot }}">{{ time_slot }}</button>
    {% endfor %}
  </div>